name: parsa
description: controle financeiro sem esforço.



publish_to: none


version: 2.0.15+88


environment:
  flutter: 3.22.3
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # flutter_auth: ^1.1.0
  auth0_flutter: ^1.8.0
  flutter_appauth: ^7.0.0
  flutter_dotenv: ^5.1.0
  flutter_pluggy_connect: ^3.0.1
  webview_flutter: ^4.10.0

  # General
  cupertino_icons: ^1.0.0
  collection: ^1.18.0
  equatable: ^2.0.5
  path: ^1.8.2
  async: ^2.10.0
  rxdart: ^0.28.0

  # i18n
  intl: ^0.19.0
  slang: ^3.30.1
  slang_flutter: ^3.30.1

  # Drift
  drift: ^2.8.1
  path_provider: ^2.0.13
  http: ^1.1.2
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.18

  # Other
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  permission_handler: ^11.3.0
  json_annotation: ^4.9.0
  fl_chart: ^0.68.0
  file_picker: ^8.0.3
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  uuid: ^4.4.2
  csv: ^6.0.0
  dotted_border: ^2.0.0+3
  package_info_plus: ^8.0.1
  introduction_screen: ^3.1.11
  dynamic_color: ^1.7.0
  copy_with_extension: ^5.0.4
  freezed_annotation: ^2.4.1
  in_app_purchase: ^3.1.11
  app_links: ^6.3.2
  flutter_secure_storage: ^9.2.2
  material_design_icons_flutter: ^7.0.0
  shared_preferences: ^2.3.2
  local_auth: ^2.3.0
  timezone: ^0.9.4
  provider: ^6.1.2
  sentry_flutter: ^8.10.1
  in_app_purchase_storekit: ^0.3.20+2
  in_app_review: ^2.0.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_in_app_messaging: ^0.8.0+5
  device_info_plus: ^10.0.0
  go_router: ^14.8.1
  timeago: ^3.7.0
  flutter_branch_sdk: ^8.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Generators:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1 # Package to regenerate icons (config later in this file). To run, type `dart run flutter_launcher_icons`
  drift_dev: ^2.13.2
  slang_build_runner: ^3.18.0 # To regenerate the translations run 'dart run slang'
  copy_with_extension_gen: ^5.0.4
  freezed: ^2.4.5

build:
  ios:

    build-name: 2.0.15
    build-number: 88
  android:
    build-name: 2.0.15
    build-number: 88



flutter_launcher_icons:
  image_path: 'assets/resources/appIcon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/resources/
    - assets/icons/onboarding/
    - assets/icons/avatars/
    - assets/icons/currency_flags/
    - assets/icons/page_states/
    - assets/icons/supported_selectable_icons/entertainment/
    - assets/icons/supported_selectable_icons/other/
    - assets/icons/supported_selectable_icons/money/
    - assets/icons/supported_selectable_icons/food/
    - assets/icons/supported_selectable_icons/medical/
    - assets/icons/supported_selectable_icons/transport/
    - assets/icons/supported_selectable_icons/technology/
    - assets/icons/supported_selectable_icons/logos/open/
    - assets/icons/supported_selectable_icons/logos/open/marca_positiva_open_finance.svg
    - assets/icons/supported_selectable_icons/logos/open/marca_open_finance.svg
    - assets/icons/supported_selectable_icons/logos/open/logo.png
    - assets/icons/supported_selectable_icons/logos/financial_institutions/
    - assets/icons/supported_selectable_icons/logos/financial_institutions/611.svg
    - assets/institutions/
    - assets/png_icons/
    - assets/sql/
    - assets/sql/migrations/
    - .env
    - lib/app/onboarding/questions.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
