import json
import os
import aiohttp
import asyncio
import colorama
from aiofiles import open as aio_open
from pathlib import Path

current_path = Path(__file__).parent.resolve()

# Function to download a single icon asynchronously
async def download_icon(session, el, new_path):
    # Skip custom scopes
    if el['scope'].startswith("logos/"):
        print(f"🔵 Skipping custom scope: {el['scope']}/{el['id']}")
        return

    url = f"https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{el['id']}/fill1/48px.svg"
    
    try:
        async with session.get(url) as response:
            if response.status != 200:
                print(colorama.Back.RED, "CURRENT PATH", colorama.Back.LIGHTRED_EX, current_path, colorama.Style.RESET_ALL)
                print(f"🔴 Icon {el['scope']}/{el['id']} skipped (HTTP {response.status})")
                return

            # Create directory if it doesn't exist
            scope_path = new_path / el['scope']
            scope_path.mkdir(parents=True, exist_ok=True)

            file_path = scope_path / f"{el['id']}.svg"
            async with aio_open(file_path, "wb") as f:
                content = await response.read()
                await f.write(content)
                print(colorama.Back.BLUE, "CURRENT PATH", colorama.Back.LIGHTBLUE_EX, current_path, colorama.Style.RESET_ALL)
                print(colorama.Back.LIGHTGREEN_EX + f"{file_path}" + colorama.Style.RESET_ALL)
                print(f"✅ Icon {el['scope']}/{el['id']} downloaded successfully")

    except Exception as e:
        print(f"⚠️ Error downloading {el['scope']}/{el['id']}: {e}")

# Asynchronous function to download all icons concurrently
async def download_google_font_icons(data, path: str):
    new_path = current_path / path
    print(f"Saving icons to: {new_path}")

    async with aiohttp.ClientSession() as session:
        tasks = [download_icon(session, el, new_path) for el in data]
        await asyncio.gather(*tasks)

# Run the async function
def main():
    # Load supported icons
    with open(current_path / "supported_icons.json", "r") as f:
        data = json.load(f)

    # Run the download in the event loop
    asyncio.run(download_google_font_icons(data, "./../../../../../assets/icons/supported_selectable_icons"))

    # Generate Dart file
    with open(current_path / "supported_icons.dart", "wb") as dart_file:
        dart_file.write(
            """// * DO NOT EDIT THIS FILE. 
//
// To re-generate it, please check the python script under services/utils/icon_downloader

""".encode()
        )
        dart_file.write(
            "/// List of all the supported icons in the app. This list does not take into account app functionality icons, just the icons that are selectable to identificate some accounts, categories...\n".encode()
        )
        dart_file.write("List<Map<String, dynamic>> supportedIcons = ".encode())
        dart_file.write(str(data).encode())
        dart_file.write(";".encode())

if __name__ == "__main__":
    main()