import json
import os
import requests
import colorama

current_path = os.path.dirname(os.path.abspath(__file__))

def download_google_font_icons(data, path: str):
    new_path = os.path.join(current_path, path)
    print(new_path)

    for el in data:
        # Skip custom scopes
        if el['scope'].startswith("logos/"):
            print(f"🔵 Skipping custom scope: {el['scope']}/{el['id']}")
            continue

        url = f"https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{el['id']}/fill1/48px.svg"
        response = requests.get(url)

        if response.status_code != 200:
            print(colorama.Back.RED, "CURRENT PATH", colorama.Back.LIGHTRED_EX, current_path, colorama.Style.RESET_ALL)
            print(f"🔴 Icon {el['scope']}/{el['id']} skipped because it does not exist in the source.")
            continue

        scope_path = os.path.join(new_path, el['scope'])
        os.makedirs(scope_path, exist_ok=True)

        file_path = os.path.join(scope_path, f"{el['id']}.svg")
        with open(file_path, "wb") as f:
            print(colorama.Back.BLUE, "CURRENT PATH", colorama.Back.LIGHTBLUE_EX, current_path, colorama.Style.RESET_ALL)
            print(colorama.Back.LIGHTGREEN_EX + f"{file_path}" + colorama.Style.RESET_ALL)
            f.write(response.content)
            print(f"✅ Icon {el['scope']}/{el['id']} downloaded successfully")

# Load supported icons
with open(os.path.join(current_path, "supported_icons.json"), "r") as f:
    data = json.load(f)

download_google_font_icons(data, "./../../../../../assets/icons/supported_selectable_icons")

# Generate Dart file
with open(os.path.join(current_path, "supported_icons.dart"), "wb") as dart_file:
    dart_file.write(
        """// * DO NOT EDIT THIS FILE. 
//
// To re-generate it, please check the python script under services/utils/icon_downloader

""".encode()
    )
    dart_file.write(
        "/// List of all the supported icons in the app. This list does not take into account app functionality icons, just the icons that are selectable to identificate some accounts, categories...\n".encode()
    )
    dart_file.write("List<Map<String, dynamic>> supportedIcons = ".encode())
    dart_file.write(str(data).encode())
    dart_file.write(";".encode())